# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exposure_progression_listener_cpp_internal <- function(health, exposure_progression) {
    .Call(`_yellowfeverIBM_exposure_progression_listener_cpp_internal`, health, exposure_progression)
}

exposure_infection_progression_process_cpp <- function(health, exposure_progression, gamma_shape, gamma_scale, dt) {
    .Call(`_yellowfeverIBM_exposure_infection_progression_process_cpp`, health, exposure_progression, gamma_shape, gamma_scale, dt)
}

exposure_process_cpp <- function(health, beta, N, dt) {
    .Call(`_yellowfeverIBM_exposure_process_cpp`, health, beta, N, dt)
}

