# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multi_probability_multinomial_process_internal <- function(variable, source_state, destination_states, rate_variable, destination_probabilities) {
    .Call(`_yellowfeverIBM_multi_probability_multinomial_process_internal`, variable, source_state, destination_states, rate_variable, destination_probabilities)
}

